# -*- coding: utf-8 -*-
# :Project:   python-rapidjson -- Gitlab CI configuration
# :Author:    Lele Gaifax <lele@metapensiero.it>
# :License:   MIT License
# :Copyright: Â© 2017, 2018 Lele Gaifax
#

# When the master branch is tagged, build the Python 3.6 wheels and upload
# them to PyPI.
#
# This is a workaround to an issue in building those wheels on Travis CI, see
# https://mail.python.org/pipermail/wheel-builders/2017-August/000285.html

stages:
  - deploy

variables:
  CIBW_OUTPUT_DIR: wheelhouse
  CIBW_PLATFORM: linux
  CIBW_SKIP: "cp2* cp33* cp34* cp35*"
  CIBW_TEST_COMMAND: "python -c 'import rapidjson; print(rapidjson.__version__)'"
  TWINE_USERNAME: lelit
  # Note: TWINE_PASSWORD is set in Gitlab settings

build:
  stage: deploy
  only:
    - tags
  script:
    - git submodule update --init --recursive
    - python3 -m venv env
    - env/bin/pip install cibuildwheel==0.9.3 twine
    - env/bin/cibuildwheel
    - env/bin/twine upload wheelhouse/*.whl
