# -*- coding: utf-8 -*-
# :Project:   python-rapidjson -- Configuration to build and upload wheels to PyPI
# :Author:    Lele Gaifax <lele@metapensiero.it>
# :License:   MIT License
# :Copyright: Â© 2017, 2018, 2019, 2020 Lele Gaifax
#

# Here we execute the Python 3.6 tests; Python 3.7, 3.8 and 3.9 tests are run by
# cibuildwheel, inside the manylinux1 Docker image.
#
# We also run tests for memory leaks, which require a debug build of Python.

dist: bionic

matrix:
  include:
    - sudo: required
      language: python
      python: "3.6"
      services:
        - docker
    - language: python
      python: "3.6"
      env: RUN_DEBUG_PYTHON=true
    - os: osx
      python: "3.8"

env:
  global:
    - CIBW_TEST_REQUIRES="pytest pytest-benchmark pytz"
    - CIBW_TEST_COMMAND="py.test {project}/tests"
    - CIBW_SKIP="cp2* cp33* cp34* cp35* pp*"
    - TWINE_USERNAME=lelit
      # Note: TWINE_PASSWORD is set in Travis settings

install:
  - |
    if [ $RUN_DEBUG_PYTHON = true ]; then
      sudo apt-get install python3-dbg
      virtualenv -p python3-dbg /tmp/env
      . /tmp/env/bin/activate
    fi
  - pip3 install -r requirements-test.txt

script:
  - pip3 install .
  - pytest tests
  - pushd docs
  - make doctest -e PYTHON=$(which python3)
  - popd
  # cibuildwheel's docker might get confused and throw an ImportMismatchError,
  # so we remove bytecode files before running it.
  - find . -name __pycache__ -exec rm -rf {} +
  - |
    pip3 install cibuildwheel==1.7.1
    cibuildwheel --output-dir wheelhouse
    if [[ -n "$TRAVIS_TAG" && -z "$RUN_DEBUG_PYTHON" ]]; then
      pip3 install twine
      python3 -m twine upload wheelhouse/*.whl
    fi
