# -*- coding: utf-8 -*-
# :Project:   python-rapidjson -- Configuration to build and upload Windows wheels to PyPI
# :Author:    Lele Gaifax <lele@metapensiero.it>
# :License:   MIT License
# :Copyright: Â© 2017 Lele Gaifax
#

environment:
  CIBW_TEST_REQUIRES: "pytest pytz"
  CIBW_TEST_COMMAND: "py.test {project}\\tests"
  CIBW_SKIP: "cp2* cp33*"
  TWINE_USERNAME: lelit
  # Note: TWINE_PASSWORD is set in Appveyor settings
  matrix:
    - PYTHON: "C:\\Python35-x64\\python.exe"

install: "git submodule update --init --recursive"

build_script:
  - "%PYTHON% -m pip install cibuildwheel==0.7.0"
  - "%PYTHON% -m cibuildwheel --output-dir wheelhouse"
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true") {
        pip install twine
        twine upload (resolve-path wheelhouse\*.whl)
      }

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels
